services:
  - type: web
    name: ai-resume-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: "https://<your-backend-url>/auth/google/callback"
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: ai-resume-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: VITE_API_URL
        value: "https://<your-backend-url>"
